### ISSUE TITLE
如果suppressMacOS为true，scrollbar显示什么样子？

### ISSUE THREAD

**Issue by xinlong-chen865** [MinJieLiu/mac-scrollbar#1]
如果suppressMacOS为true，我看是返回一个
`<div style={currentStyle} ref={ref} {...props}>
         {children}
        </div>
`
这样的组件，我理解的是，直接利用浏览器自身的scrollbar，对吗？

**Comment by MinJieLiu** [comment]
只有在 macOS 上面会直接使用自身的 scrollbar
