### ISSUE TITLE
CRA编译失败

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#10]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13760476/156594499-3bc75cd5-fb39-4edc-a329-fabc28cf379e.png">

执行`yarn build`后报错

问题复现地址 [https://github.com/usercao/react-test](https://github.com/usercao/react-test)

### vite build可以正常编译通过

**Comment by MinJieLiu** [comment]
https://github.com/facebook/create-react-app/discussions/10095

**Comment by usercao** [comment]
thanks🙏
