### ISSUE TITLE
滚动条被页面裁减

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#11]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/13760476/156317450-2b6fd695-0530-482b-a7d1-0658718c7d72.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/13760476/156693243-3fdda9be-041b-45a2-8d4b-e5c825edc68a.png">

希望在只有单个滚动条的情况下与页面也能有一定间隔，因为浏览器的边角是圆角裁切了部分(或者有圆角的弹窗等)，移动到底部时导致看不完全滚动条，设置了`trackEndGap`这个参数后页面没有明显变化。

**Comment by usercao** [comment]
<img width="214" alt="image" src="https://user-images.githubusercontent.com/13760476/156909586-5ddb7266-3003-4eca-9467-92894f1600ee.png">

上下左右可能都需要边距，因为是4个圆角

**Comment by MinJieLiu** [comment]
0.10.0
