### ISSUE TITLE
mac-scrollbar 包裹 textarea 作为输入组件滚动条，top 计算误差

### ISSUE THREAD

**Issue by Saszr** [MinJieLiu/mac-scrollbar#12]
### Reproduction link

[open in stackblitz](https://stackblitz.com/edit/vitejs-vite-1aknfh?file=src/App.tsx)

### Steps to reproduce

mac-scrollbar 包裹 textarea 作为输入组件滚动条。
textarea 自适应高度需要动态设置 height，页面渲染导致 mac-scrollbar 位置重新计算，top 计算存在误差 🤔

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/159268672-18bbe47d-b178-4ea4-8e21-7708bb701f9b.png)
感觉正常的

**Comment by Saszr** [comment]
![2022-03-21 21 21 32](https://user-images.githubusercontent.com/22406550/159269863-3cbbc009-6487-4634-b264-1210fb420e4c.gif)

**Comment by MinJieLiu** [comment]
这个行为和原生滚动条一样，没有经过特别的计算

**Comment by MinJieLiu** [comment]
这里高度变化，不应该设置top，我改下

**Comment by MinJieLiu** [comment]
@Saszr 不对，你把 Macscrollbar 换成 div 仍然是这样的效果

**Comment by MinJieLiu** [comment]
这应该属于元素自动焦点的行为
