### ISSUE TITLE
自定义滚动条能否增加边距

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#13]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/13760476/165030793-86273793-eb18-40a7-a8ea-d915704f1cd3.png">

希望检测到是自定义的滚动条样式的时候增加2px边距，现在都是顶满的

**Comment by usercao** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/13760476/165050533-9b60eea3-c4c0-4066-91d0-859dd30197a0.png">

很奇怪弹窗里使用滚动条又可见明显边距

**Comment by MinJieLiu** [comment]
可以通过重置样式实现，比如在 .ms-y 加个 right: 4px

**Comment by usercao** [comment]
我看了文档不太清楚.ms-y加在哪里，也没在dom里面找到这个class

**Comment by MinJieLiu** [comment]
```js
trackStyle={(horizontal) => ({ [horizontal ? 'height' : 'width']: 0, right: 2, border: 0 })}
thumbStyle={(horizontal) => ({ [horizontal ? 'height' : 'width']: 4 })}
```

**Comment by usercao** [comment]
解决了thanks🙏
