### ISSUE TITLE
不符合预期的显示效果

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#15]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/13760476/172757467-0fabba0a-a600-47bb-9d0a-f2e13fff29de.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/13760476/172757388-a8133a0e-f482-463c-87dc-3a34c3339045.png">

```jsx
<MacScrollbar
  trackStyle={(horizontal) => ({ [horizontal ? "height" : "width"]: 0 })}
  thumbStyle={(horizontal) => ({ [horizontal ? "height" : "width"]: 3 })}
  trackGap={[4, 4, 4, 4]}
>
  {cloneElement(children)}
</MacScrollbar>;

```

黑夜模式下hover有带颜色的背景出现，白天其实也有，不过因为都是白色所以被忽略掉了

**Comment by MinJieLiu** [comment]
你可以 trackStyle 设置 borderWidth: 0

**Comment by usercao** [comment]
👍，已解决
