### ISSUE TITLE
快速上下滚动失去响应

### ISSUE THREAD

**Issue by jipiyan** [MinJieLiu/mac-scrollbar#17]
使用滚轮快速上下滚动，滚动条会暂时失去响应。过1-2s重新可以响应，不知道是不是计算量过大问题

**Comment by MinJieLiu** [comment]
可以先不用这个插件试试，排查下问题

**Comment by jipiyan** [comment]
使用原生的滚动条没有问题。用的是electron + antd，滚动区域是antd的Layout.Content组件。可能是electron的性能问题，用了插件会失去响应🤦🏻‍♀️，不太清楚[捂脸]

**Comment by jipiyan** [comment]
> 可以先不用这个插件试试，排查下问题

大大你好，还有一个问题，container你设置的overflow是auto，这样被包裹容器设置的阴影看不见了，把这个overflow改成visible不知道会有什么影响

**Comment by MinJieLiu** [comment]
那就没有滚动条了啊😂
