### ISSUE TITLE
如何不让鼠标移入显示滚动条

### ISSUE THREAD

**Issue by jipiyan** [MinJieLiu/mac-scrollbar#19]
大佬，当鼠标移入ms插件包裹的节点时，滚动条会立刻显示，请问如何不让鼠标移入显示滚动条，而是在滚轮滚动时才显示

**Comment by MinJieLiu** [comment]
目前是设定好的，你可以clone 一份修改

**Comment by jipiyan** [comment]
> 目前是设定好的，你可以clone 一份修改

了解，谢谢大佬
