### ISSUE TITLE
need an "as" prop

### ISSUE THREAD

**Issue by librz** [MinJieLiu/mac-scrollbar#2]
Current, MacScrollBar servers as a div container & inject the actual scrollbar element as its child.

The problem is it's always a "div" element, I haven't found a way to custimize the element type.

Can you provide an "as" prop that let me customize the element type? After all, html5 semantic tags are there for a reason.

Something like this will do:

```react
<MacScrollbar as="main">
  <div>
   {content}
  </div>
</MacScrollbar>
```

**Comment by MinJieLiu** [comment]
👌

**Comment by MinJieLiu** [comment]
0.7.3
