### ISSUE TITLE
未考虑完善的使用情况导致报错

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#20]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/13760476/188824308-2f3aed0f-1eae-4b93-9d15-487a7ec57f7d.png">

如上图所示使用会报错`<div> cannot appear as a child of <tbody>`

**Comment by MinJieLiu** [comment]
tbody 里面不允许添加任何节点，这就有点尴尬了

**Comment by usercao** [comment]
如果想实现固定thead，只有tbody滚动的情况下使用，有没有什么想法？

**Comment by MinJieLiu** [comment]
antd 用了两个表格

**Comment by usercao** [comment]
看了下是这样的，感觉不太优雅，还是用div自定义table吧，thanks
