### ISSUE TITLE
请问具体如何将thumb定位到底部

### ISSUE THREAD

**Issue by twigsWHy** [MinJieLiu/mac-scrollbar#21]
![image](https://user-images.githubusercontent.com/52269319/192282032-06ff24e1-8523-44ea-a83d-7780c9fcb24d.png)
我看到您在这个已经关闭的issue中提到可以拿到滚动条的div 的 ref，请问更具体地需要如何拿到滚动条的div 的 ref？

**Comment by MinJieLiu** [comment]
<MacScrollbar ref={ref}> ...</MacScrollbar>

**Comment by twigsWHy** [comment]
> 

我使用了这种方式，但是直接或得到的是整个ms-container的ref，对这个ref.current.scrollTop进行赋值是无效的

**Comment by MinJieLiu** [comment]
说错了，你试试 `ref.current.scrollTo(0, 100)`
