### ISSUE TITLE
Is there any way to set fixed width or max-width to thumb?

### ISSUE THREAD

**Issue by kr4chinin** [MinJieLiu/mac-scrollbar#25]
I am using `<GlobalScrollba />` component, it is too large when there is only a small overflow:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/103210607/213779457-e327fb0a-c397-4202-a274-549fd36c915c.gif)

When I am trying to **customize** width by setting it like a so...

```
     <GlobalScrollbar
        thumbStyle={vertical => {
          if (vertical) {
            return {
              width: '200px'
            };
          }

          return {
            backgroundColor: '#AAB7D4',
          };
        }}
      />
```

... I am getting this strange behavior:

![width_issue](https://user-images.githubusercontent.com/103210607/213779642-e5cde890-daa0-4a60-93a0-541ad60cd547.gif)

Is there any way I can set `width` or `max-width` properly?

**Comment by MinJieLiu** [comment]
This is consistent with the native scrollbar interaction.
Your strange behavior could be caused by the rapid change in width
