### ISSUE TITLE
请问可以转为JavaScript形式吗？

### ISSUE THREAD

**Issue by txunda** [MinJieLiu/mac-scrollbar#26]
我更换打包方式了之后运行报错呢怎么
<img width="470" alt="image" src="https://user-images.githubusercontent.com/76721805/220578169-d2fb8b68-6e10-46bb-84be-16698a574832.png">

**Comment by MinJieLiu** [comment]
这个是打包配置问题，因为 react 中的 process.env.NODE_ENV 没有被转换掉
