### ISSUE TITLE
请问可以全局使用吗

### ISSUE THREAD

**Issue by Jerry-is-coming** [MinJieLiu/mac-scrollbar#27]

**Comment by MinJieLiu** [comment]
可以，可以看看 demo

**Comment by Jerry-is-coming** [comment]
![image](https://user-images.githubusercontent.com/33172156/222628698-6fb98874-7048-4c0f-b91d-fb2609652bba.png)
使用GlobalScrollbar 只有window窗口滚动条，其他的滚动条仍是浏览器默认样式
