### ISSUE TITLE
Next.js使用GlobalScrollbar报错

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#32]
![image](https://github.com/MinJieLiu/mac-scrollbar/assets/13760476/a3f7e63c-f4bb-4685-a591-9f24f29e9db9)
```tsx
import { GlobalScrollbar } from 'mac-scrollbar';
import 'mac-scrollbar/dist/mac-scrollbar.css';

return <GlobalScrollbar />;
```
`0.12.5`版本在Next.js中使用会报水合错误，`0.12.3`没有此问题。

**Comment by MinJieLiu** [comment]
fix: 0.13.5
