### ISSUE TITLE
能否考虑添加一种全局的样式配置方式

### ISSUE THREAD

**Issue by lopo12123** [MinJieLiu/mac-scrollbar#33]
感谢作者提供这个库。

目前我有多个页面用到了这个滚动条，比如宽度高度样式之类的设置每次都复制一下感觉不是很优雅，能否考虑添加一种使用js以全局的方式来配置的功能。

目前想到了两种设计，
一种是使用类似 ThemeProvider 的方法，在最外层包裹。好处是可以响应式变更，缺点是需要多一层嵌套包裹，并且对于后续转换成多框架通用会带来负担（如果作者有这个考虑的话）；
另一种是暴露一个类（一个抽象类或者单例）提供默认值并允许用户修改它，在各组件的内部按照 (组件配置 > 全局配置 > 默认) 的顺序来得到最终生效的值。

**Comment by MinJieLiu** [comment]
两种都不好，第二种更是增加复杂度。
你可以直接将 <MacScrollbar /> 多封装一层，全局都调用你封装好的组件就可以了。这样还可以降低复杂度，也不损失灵活度
