### ISSUE TITLE
滚动条样式建议

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#4]
![image](https://user-images.githubusercontent.com/13760476/144198178-0eb58525-2ebd-4e2e-823e-f1e02a02ea1a.png)
同时存在XY轴滚动条到角落的时候会叠在一起，参照网址https://kingsora.github.io/OverlayScrollbars/#!themes
![image](https://user-images.githubusercontent.com/13760476/144198370-453739e5-043f-4fb2-abd6-ba6c55075698.png)
能否提供两种细一点的样式可以放在select之类的组件中使用

**Comment by MinJieLiu** [comment]
考虑优化它

**Comment by usercao** [comment]
@MinJieLiu `XY轴滚动条到角落的时候会叠在一起`的修复有计划时间吗？

**Comment by MinJieLiu** [comment]
@usercao 年前应该有时间

**Comment by usercao** [comment]
> @usercao 年前应该有时间

nice👍，滚动条宽度与hover上去的滚动条背景(关闭)也可以加两个配置项，这样就可以在select里面使用了

**Comment by MinJieLiu** [comment]
ok

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/mac-scrollbar/releases/tag/v0.9.0
