### ISSUE TITLE
类型识别不正确

### ISSUE THREAD

**Issue by hey-feitian** [MinJieLiu/mac-scrollbar#5]
`/mac-scrollbar@0.8.0/node_modules/mac-scrollbar/src/utils.tsx(57,19)`
`      TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.`

https://github.com/MinJieLiu/mac-scrollbar/blob/main/packages/mac-scrollbar/src/utils.tsx#L64

**Comment by MinJieLiu** [comment]
我换一种编译方式吧。把 d.ts 放出来，放源码类型各种问题

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/mac-scrollbar/releases/tag/v0.9.0
