### ISSUE TITLE
宽度计算问题

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#6]
![image](https://user-images.githubusercontent.com/13760476/149302687-61dc8e14-3d8d-4fa1-b565-4f008c38cc9c.png)
父级宽度和子级宽度都是100%的时候会出x轴滚动条，大概有1px的移动距离

**Comment by usercao** [comment]
设置实例中的`suppressScrollX={false}`就可以看到 #5

**Comment by MinJieLiu** [comment]
这个示例中我没有重现这个问题
