### ISSUE TITLE
类型定义冲突

### ISSUE THREAD

**Issue by usercao** [MinJieLiu/mac-scrollbar#7]
![image](https://user-images.githubusercontent.com/13760476/149314833-c679d2ba-8fc5-4456-8d89-3e52aced45de.png)
类型定义名称`theme` `as`与`styled-components`起冲突，最小实例地址:[https://github.com/usercao/ice-test](https://github.com/usercao/ice-test)

**Comment by MinJieLiu** [comment]
看来得换名字咯

**Comment by MinJieLiu** [comment]
theme 不冲突， as 可以用 forwardedAs 代替

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/151313398-59029367-b24a-4b2e-90e5-aa00e58a9872.png)

**Comment by MinJieLiu** [comment]
theme 还是换个名字吧，表现形式还不一样

**Comment by usercao** [comment]
自定义滚动条宽度和固定的滚动容器高度[例如select里防止继续resize高度]可以考虑下

**Comment by MinJieLiu** [comment]
固定的容器高度[select里防止继续resize高度] 场景体现在哪里，select 高度会一直 resize 吗

**Comment by usercao** [comment]
> 固定的容器高度[select里防止继续resize高度] 场景体现在哪里，select 高度会一直 resize 吗

我的错，我猜的会不会有这个问题，因为没有细滚动条还没写过select

**Comment by MinJieLiu** [comment]
https://github.com/MinJieLiu/mac-scrollbar/releases/tag/v0.9.0

**Comment by usercao** [comment]
@MinJieLiu forwardedAs没搞明白如何使用，我这样使用会触发TS类型错误
```ts
<Scrollbar forwardedAs='ul'>
  <div style={{ height: 2000 }}>{children}</div>
</Scrollbar>
```
```ts
const Wrapper = styled(MacScrollbar)<ScrollbarProps>`
  height: inherit;
`;

const Scrollbar: React.FC<ScrollbarProps> = (props: ScrollbarProps) => {
  const { forwardedAs,children, ...rest } = props;
  return (
    <Wrapper forwardedAs={'li'} {...rest}>
      {children}
    </Wrapper>
  );
};
```
最小实例地址[https://github.com/usercao/ice-test](https://github.com/usercao/ice-test)

**Comment by usercao** [comment]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/13760476/156157383-9216a60c-d606-406b-abf4-57a80a9ba615.png">
同时新版下会有如下警告

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/156172774-788c5d0d-83c1-4bf6-811e-75569951aff9.png)

示例里面没复现，有复现的仓库吗

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/156178355-76b52cf4-38af-42d8-acf5-06ba66917b98.png)
我觉得这是 vite 的问题，因为 在导出的 css 中提供了 map 文件，vite 没有正确解析

**Comment by usercao** [comment]
那这个能如何避免呢？我现在重新create了一个项目看看会不会这个问题消失了

**Comment by MinJieLiu** [comment]
https://github.com/vitejs/vite/pull/659

**Comment by usercao** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/13760476/156179864-17f57e57-219d-4dcc-9323-dd652b31c61c.png">
还是有这个问题

**Comment by usercao** [comment]
> [vitejs/vite#659](https://github.com/vitejs/vite/pull/659)

感谢🙏我明白了，请问可以看一下forwardedAs为什么类型错误吗？

**Comment by MinJieLiu** [comment]
有仓库吗

**Comment by usercao** [comment]
> https://github.com/usercao/ice-test

https://github.com/usercao/ice-test就是这个仓库里面的scrollbar组件

**Comment by MinJieLiu** [comment]
```js
const Scrollbar: React.FC<ScrollbarProps> = (props: ScrollbarProps) => {
  const { as, children, ...rest } = props;
  return (
    <Wrapper forwardedAs={as as keyof JSX.IntrinsicElements} {...rest}>
      {children}
    </Wrapper>
  );
};
```
